### ISSUE TITLE
Possibility to run the tool on older OS

### ISSUE THREAD

**Issue by greenozon** [AlSch092/UltimateAntiCheat#10]
for example it does not like w7:

```
---------------------------
UltimateAnticheat.exe - Entry Point Not Found
---------------------------
The procedure entry point SetProcessMitigationPolicy could not be located in the dynamic link library KERNEL32.dll. 
---------------------------
OK   
---------------------------
```

**Comment by AlSch092** [comment]
This routine isn't available in windows 7; feel free to comment it out for now. I'll add a '_WIN32_WINNT' check to this when I next have some free time.

**Comment by AlSch092** [comment]
The define  _WIN32_WINNT=0x0A00; was added to preprocessor definitions, which in turn will remove `EnableProcessMitigations` from compilation. Please change this to _WIN32_WINNT=0x0601 if you're targeting Windows 7.

Cheers
