### ISSUE TITLE
_CRT_SECURE_NO_WARNINGS macro redefinition

### ISSUE THREAD

**Issue by greenozon** [AlSch092/UltimateAntiCheat#12]
There are 2 defines of the same macro in different files:

```
1>c:\Dev\UltimateAntiCheat\Process\PEB.hpp(3,1): warning C4005: '_CRT_SECURE_NO_WARNINGS': macro redefinition
1>c:\Dev\UltimateAntiCheat\main.cpp : message : see previous definition of '_CRT_SECURE_NO_WARNINGS'
```

idea:  define this macro on project level, so each & every module will have it defined

**Comment by AlSch092** [comment]
It will be moved into preprocessor definitions, thanks for your input.
