### ISSUE TITLE
VirtualProtect Fails with ERROR_INVALID_ADDRESS 

### ISSUE THREAD

**Issue by v3ctra** [AlSch092/UltimateAntiCheat#15]
Hello. 
The following line fails with code ERROR_INVALID_ADDRESS / 487 / (0x1E7)
https://github.com/AlSch092/UltimateAntiCheat/blob/main/main.cpp#L235

I had no enough time to investigate this myself, maybe ThreadExecutionAddressStackOffset is wrong.
OS: Windows 11 23H2 (22631.2861).

**Comment by AlSch092** [comment]
Hi,

Yes, most likely the offset for the thread's execution address is different on your operating system. I don't have Windows 11 to fix this, so either you can comment that section out, or set UnmanagedGlobals::SuppressingThreads to false. If you want to try and fix it, you'll have to breakpoint on the TLS callback where ThreadExecutionAddress is set and view the stack for the offset of the thread's to-be executed routine address.

Cheers
