### ISSUE TITLE
Unresolved external CheckForDebugger

### ISSUE THREAD

**Issue by ShamaIow** [AlSch092/UltimateAntiCheat#3]
Can you give the function for static void CheckForDebugger(LPVOID AD); ?

Error LNK2019	unresolved external symbol "public: static void __cdecl Debugger::AntiDebug::CheckForDebugger(void *)" (?CheckForDebugger@AntiDebug@Debugger@@SAXPEAX@Z) referenced in function "public: void __cdecl Debugger::AntiDebug::StartAntiDebugThread(void)" (?StartAntiDebugThread@AntiDebug@Debugger@@QEAAXXZ)

**Comment by AlSch092** [comment]
Greetings,

Please check now, the project has been reuploaded in full

Regards,
