### ISSUE TITLE
Access violation error

### ISSUE THREAD

**Issue by ShamaIow** [AlSch092/UltimateAntiCheat#4]
Hello, thanks for updating first!

Platform: x64 
C++ 14
Unicode chars set
Debug definitions: _CRT_SECURE_NO_WARNINGS and _WINSOCK_DEPRECATED_NO_WARNINGS

While trying to see if everything works, i got access violation at AntiCheat::IsVTableHijacked((void*)g_AC) or AntiCheat::RemapAndCheckPages();. I can't figure it out i'm too bad in C++. I built an exe like the release you made and i get this error for the function IsVTableHijacked:

Exception thrown at 0x00007FFF9E06D0B5 (ucrtbased.dll) in UltimateAnticheat.exe: 0xC0000005: Access violation writing location 0x00000182984A4430.
![image](https://github.com/AlSch092/UltimateAntiCheat/assets/46390986/8f261b39-edc3-4958-a415-b14f3dbb4947)

And the second error i get is on the function AntiCheat::RemapAndCheckPages()
Exception thrown at 0x00000235BDEF4A64 in UltimateAnticheat.exe: 0xC0000005: Access violation reading location 0x00007FF727D84D10
![image](https://github.com/AlSch092/UltimateAntiCheat/assets/46390986/bb31c612-d0e7-4864-9562-73ccc5240292)

**Comment by AlSch092** [comment]
Thanks for bringing this to my attention, the routine "IsVTableHijacked" needs to be re-written in a safer way. Today's code updates have commented out that test and the function will be re-added once I can confirm it's working safely. Please view API.cpp and main.cpp for updated versions.
