### ISSUE TITLE
"AntiCheat" has no member "GetProcessObject" nor "RemapAndCheckPages"

### ISSUE THREAD

**Issue by SolocaseJR** [AlSch092/UltimateAntiCheat#5]
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	E0135	class "AntiCheat" has no member "GetProcessObject"	UltimateAnticheat	C:\Users\soloc\Downloads\UltimateAntiCheat-main\API\API.cpp	18		

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	E0135	class "AntiCheat" has no member "RemapAndCheckPages"	UltimateAnticheat	C:\Users\soloc\Downloads\UltimateAntiCheat-main\API\API.cpp	97

**Comment by AlSch092** [comment]
Greetings,

A few files needed to be uploaded (API.cpp,.hpp) as they were not the newest versions, please try downloading the .zip code and re-building with the downloaded version and it should work. I have just tried it in VS2022 with a successful release build in x64, so it should hopefully work for you this time around.

Thank you for bringing this up, if you encounter any further issues feel free to raise another topic.
